export const mockData = {
    fisica_nacional: {
        "Nombre del agente": "Ana Valdés (Portal)",
        "Nombre del ejecutivo": "Ricardo Alarcón",
        "Nombre": "",
        "Apellido paterno": "",
        "Apellido materno": "",
        "mail": "",
        "RFC": "",
        "CURP": "",
        "Giro": "",
        "Nacionalidad": "",
        "Calle": "",
        "Núm ext": "",
        "CP": "",
        "Col": "",
        "Ciudad población": "",
        "Entidad federativa": "",
        "Tel 1": "",
        "Día1": "",
        "Mes1": "",
        "Año1": "",
        "Año2": "",
        "Nombre y Firma del Cliente Contratante": ""
    },
    fisica_extranjera: {
        "Nombre del agente": "Ana Valdés (Portal)",
        "Ejecutivo de la cuenta": "Ricardo Alarcón",
        "Nombre": "",
        "Apellido paterno": "",
        "Apellido matreno": "",
        "CURP": "",
        "Actividad": "",
        "País Nacimiento": "",
        "Nacionalidad": "",
        "ID": "",
        "Calle": "",
        "Núm ext": "",
        "CP": "",
        "Colonia": "",
        "Ciudad": "",
        "Tel1": "",
        "Nombre y Firma del Cliente Contratante": ""
    },
    moral_nacional: {
        "Nombre del agente": "Ana Valdés (Portal)",
        "Nombre del ejecutivo": "Ricardo Alarcón",
        "Razón social": "",
        "RFC": "",
        "Folio mercantil": "",
        "Nacionalidad": "",
        "Giro Mercatil": "",
        "calle": "",
        "Núm Ext": "",
        "CP": "",
        "Col": "",
        "Ciudad o población": "",
        "Tel 1": "",
        "Nombre completo": "",
        "RFC representante legal": "",
        "Cargo": "",
        "Nombre y Firma del Representante Legal": ""
    },
    moral_extranjera: {
        "Nombre del agente": "Ana Valdés (Portal)",
        "Nombre del ejecutivo": "Ricardo Alarcón",
        "Razoón social": "",
        "Nacionalidad": "",
        "RFC": "",
        "Número de Certificado": "",
        "Giro": "",
        "Dirección": "",
        "mail": "",
        "Nombre": "",
        "Cargo": "",
        "Nombre y Firma del Representante Legal": ""
    }
};

export const pdfMap = {
    fisica_nacional: "personas-fisicas.pdf",
    fisica_extranjera: "personas-fisicas-extranjeras.pdf",
    moral_nacional: "personas-morales.pdf",
    moral_extranjera: "personas-morales-extranjeras.pdf"
};
