export const mockData = {
    fisica_nacional: {
        "Nombre del agente": "Ana Valdés (Portal)",
        "Nombre del ejecutivo": "Ricardo Alarcón",
        "Nombre": "ALEJANDRO",
        "Apellido paterno": "RODRÍGUEZ",
        "Apellido materno": "GARCÍA",
        "mail": "arodriguez@ejemplo.com",
        "RFC": "ROGA880512HDF",
        "CURP": "ROGA880512HDFNRG09",
        "Giro": "Servicios Profesionales",
        "Nacionalidad": "Mexicana",
        "Calle": "Insurgentes Sur",
        "Núm ext": "1602",
        "CP": "03940",
        "Col": "Crédito Constructor",
        "Ciudad población": "Ciudad de México",
        "Entidad federativa": "CDMX",
        "Tel 1": "5512345678",
        "Día1": "15",
        "Mes1": "06",
        "Año1": "20",
        "Año2": "24",
        "Nombre y Firma del Cliente Contratante": "Alejandro Rodríguez García (Firma Digital Electrónica)"
    },
    fisica_extranjera: {
        "Nombre del agente": "Ana Valdés (Portal)",
        "Ejecutivo de la cuenta": "Ricardo Alarcón",
        "Nombre": "JOHN",
        "Apellido paterno": "SMITH",
        "Apellido matreno": "",
        "mail": "john.smith@example.com",
        "RFC": "XEXX010101000",
        "CURP": "",
        "Actividad": "Consultoría IT",
        "País Nacimiento": "Estados Unidos",
        "Nacionalidad": "Estadounidense",
        "ID": "US-PASS-123456",
        "Calle": "Campos Elíseos",
        "Núm ext": "400",
        "CP": "11560",
        "Colonia": "Polanco",
        "Ciudad": "Ciudad de México",
        "Tel1": "5598765432",
        "Nombre y Firma del Cliente Contratante": "John Smith (Firma Digital Electrónica)"
    },
    moral_nacional: {
        "Nombre del agente": "Ana Valdés (Portal)",
        "Nombre del ejecutivo": "Ricardo Alarcón",
        "Razón social": "LOGÍSTICA GLOBAL S.A. DE C.V.",
        "RFC": "LGL150812XYZ",
        "Folio mercantil": "987654321",
        "Nacionalidad": "Mexicana",
        "Giro Mercatil": "Transporte y Logística",
        "calle": "Av. Paseo de la Reforma",
        "Núm Ext": "222",
        "CP": "06600",
        "Col": "Juárez",
        "Ciudad o población": "Ciudad de México",
        "Tel 1": "5544332211",
        "Nombre completo": "CARLOS MENDOZA RUIZ",
        "RFC representante legal": "MERC750101XYZ",
        "Cargo": "Director General",
        "Nombre y Firma del Representante Legal": "Carlos Mendoza Ruiz (Firma Digital Electrónica)"
    },
    moral_extranjera: {
        "Nombre del agente": "Ana Valdés (Portal)",
        "Nombre del ejecutivo": "Ricardo Alarcón",
        "Razoón social": "GLOBAL TECH HOLDINGS LLC",
        "Nacionalidad": "Estadounidense",
        "RFC": "XEXX010101000",
        "Número de Certificado": "TAX-123-456",
        "Giro": "Tecnología",
        "Dirección": "123 Innovation Drive, Silicon Valley, CA, USA",
        "mail": "contact@globaltech.com",
        "Nombre": "SARAH CONNOR",
        "Cargo": "CEO",
        "Nombre y Firma del Representante Legal": "Sarah Connor (Firma Digital Electrónica)"
    }
};

export const pdfMap = {
    fisica_nacional: "personas-fisicas.pdf",
    fisica_extranjera: "personas-fisicas-extranjeras.pdf",
    moral_nacional: "personas-morales.pdf",
    moral_extranjera: "personas-morales-extranjeras.pdf"
};
